Add CI stuff (hopefully)

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -12,83 +12,79 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  build:
+  build-kernel:
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        logging: ["", "log.scheduler"]
-        preemptive: ["", "preemptive"]
     steps:
       - name: 'Check out'
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           submodules: 'recursive'
-      - name: 'Download init exec'
-        run: curl -o ${{ github.workspace }}/init.exec -L https://github.com/popcorn-2/.github/raw/refs/heads/trunk/init_exec.exec
-      - name: 'Build'
-        env:
-          CC: clang
-          CXX: C++
-          CFLAGS: -I${{ github.workspace }}/deps/edk2/MdePkg/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include/X64 -v
-        run: |
-          init_exec=${{ github.workspace }}/init.exec ./pop.py build --arch x86_64 -v ${{ github.ref == 'refs/heads/trunk' && '--release' || '' }} --kernel-features="${{ matrix.logging }} ${{ matrix.preemptive }}"
-      - name: 'Archive live ISO'
-        if: success() && github.ref == 'refs/heads/trunk'
-        uses: actions/upload-artifact@v4
-        with:
-          name: Live ISO - ${{ matrix.logging }} ${{ matrix.preemptive }}
-          path: |
-            target/release/popcorn2.iso
-  test:
+          path: 'kernel'
+      - name: 'Install tooling'
+        uses: ./kernel/.github/actions/install-tooling
+      - name: 'Build kernel'
+        run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --local-source @core/kernel=./kernel/ build @core/kernel
+  clippy-kernel:
     runs-on: ubuntu-latest
-    permissions:
-      pull-requests: write
     steps:
       - name: 'Check out'
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           submodules: 'recursive'
-      - name: 'Install multilib and qemu'
-        run: |
-          sudo apt update
-          sudo apt install -y qemu-system-x86 ovmf
-      - name: 'Run tests'
-        env:
-          CC: clang
-          CXX: C++
-          CFLAGS: -I${{ github.workspace }}/deps/edk2/MdePkg/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include/X64
-        run: |
-          cp /usr/share/OVMF/OVMF_CODE.fd ./OVMF_CODE.fd
-          cp /usr/share/OVMF/OVMF_VARS.fd ./OVMF_VARS.fd
-          ./pop.py test --arch x86_64 -v --coverage coverage.profraw --junit junit.xml
-      - name: Test Summary
-        if: success() || failure()
-        uses: test-summary/action@v2
-        with:
-          paths: "junit.xml"
-          show: "fail, skip"
-          output: "tests.md"
-      - name: 'Archive results'
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: Test results
-          path: |
-            junit.xml
-      - name: 'Add results to PR'
-        if: (success() || failure()) && github.event_name == 'pull_request'
-        uses: mshick/add-pr-comment@v2
-        with:
-          message-path: "tests.md"
-      - name: 'Add results to workflow summary'
-        if: success() || failure()
-        run: |
-          cat tests.md >> $GITHUB_STEP_SUMMARY
-      - name: 'Archive coverage'
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: Test coverage
-          path: |
-            coverage.profraw
+          path: 'kernel'
+      - name: 'Install tooling'
+        uses: ./kernel/.github/actions/install-tooling
+      - name: 'Run clippy on kernel'
+        run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --local-source @core/kernel=./kernel/ run @core/kernel cargo clippy
+  # test:
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     pull-requests: write
+  #   steps:
+  #     - name: 'Check out'
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: 'recursive'
+  #     - name: 'Install multilib and qemu'
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install -y qemu-system-x86 ovmf
+  #     - name: 'Run tests'
+  #       env:
+  #         CC: clang
+  #         CXX: C++
+  #         CFLAGS: -I${{ github.workspace }}/deps/edk2/MdePkg/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include/X64
+  #       run: |
+  #         cp /usr/share/OVMF/OVMF_CODE.fd ./OVMF_CODE.fd
+  #         cp /usr/share/OVMF/OVMF_VARS.fd ./OVMF_VARS.fd
+  #         ./pop.py test --arch x86_64 -v --coverage coverage.profraw --junit junit.xml
+  #     - name: Test Summary
+  #       if: success() || failure()
+  #       uses: test-summary/action@v2
+  #       with:
+  #         paths: "junit.xml"
+  #         show: "fail, skip"
+  #         output: "tests.md"
+  #     - name: 'Archive results'
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Test results
+  #         path: |
+  #           junit.xml
+  #     - name: 'Add results to PR'
+  #       if: (success() || failure()) && github.event_name == 'pull_request'
+  #       uses: mshick/add-pr-comment@v2
+  #       with:
+  #         message-path: "tests.md"
+  #     - name: 'Add results to workflow summary'
+  #       if: success() || failure()
+  #       run: |
+  #         cat tests.md >> $GITHUB_STEP_SUMMARY
+  #     - name: 'Archive coverage'
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Test coverage
+  #         path: |
+  #           coverage.profraw
